print("*" * 40)
print("*" + " " * 38 + "*")
print("*" + "       WELCOME TO MY PROGRAM!       ".center(38) + "*")
print("*" + " " * 38 + "*")
print("*" * 40)
print()
print("        >>> Hello, World! <<<")
print()
print("*" * 40)
print("*" + "         Have a great day!          ".center(38) + "*")
print("*" * 40)
